/** @file
*
*  The ncurses applciation with entrypoint at function renderer.
*  That function can be used along with TermProgram.
*
*  @author Piotr Styczyński <piotrsty1@gmail.com>
*  @copyright MIT
*  @date 2018-04-29
*/
#ifndef __RENDERER__
#define __RENDERER__

#include <iomanip>
#include <sstream>
#include <ncurses.h>
#include <iostream>
#include <unistd.h>
#include <ncurses.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <fcntl.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/stat.h>

/**
 * Options for the ncurses application
 */
struct RendererOptions {
  bool noSplash = false;
  bool noColors = false;
} rendererOptions;

int menu1(int, TermProgram&);
int menu2(int, TermProgram&);

/**
 * Message displayed under the menu
 */
std::string menu_message = "                         ";

/**
 * Display splash and terminate applciation.
 */
void menu_end(TermProgram& program) {
  time_t t;
  srand((unsigned) time(&t));
  
  clear();
  refresh();
  
  // Generate reverse splash with ' ' characters
  int len = 0;
  for(int t=0;t<1000;++t) {
    move(rand() % 25 + 1, rand() % 75 + 5);
    addch(' ');
    usleep(100);
    refresh();
  }
  
  // Ensure entire splash box is empty
  for(int y=1;y<=25;++y) {
    for(int x=5;x<=80;++x) {
      move(y, x);
      addch(' ');
    }
  }
  
  // Trigger refresh to redraw the cleared splash box
  refresh();

  // Print good bye message
  usleep(100000);
  mvprintw(5, 15, "GOODBYE :)");
  mvprintw(7, 10, "Please feel free to leave a feedback.");
  mvprintw(8, 10, "I would like to know about your telnet experiences.");
  mvprintw(9, 10, "Have a nice day!");
  mvprintw(11, 15, "Piotr Styczynski");
  refresh();
  
  // Wait and then exit
  usleep(3500000);
}

/**
 * Display splash and start the applciation.
 */
void menu_start(TermProgram& program) {
  
  // Check if splash is enabled
  if(!rendererOptions.noSplash) {
  
    time_t t;
    srand((unsigned) time(&t));
    
    // Displays randomized # characters splash
    clear();
    int len = 0;
    for(int t=0;t<1000;++t) {
      move(rand() % 25 + 1, rand() % 75 + 5);
      addch('#');
      usleep(100);
      refresh();
    }
    
    // Fill entire block with # at the end
    for(int y=1;y<=25;++y) {
      for(int x=5;x<=80;++x) {
        move(y, x);
        addch('#');
      }
    }
    refresh();
  
  }
  
  // Start initial menu
  menu1(0, program);
}

/**
 * Display selection menu for given list of options and their descriptions.
 */
int displayMenu(std::string list[], std::string descriptions[], int first_opt, TermProgram& program) {
  
  // Render # block generated by splash
  for(int y=1;y<=25;++y) {
    for(int x=5;x<=80;++x) {
      move(y, x);
      addch('#');
    }
  }
  refresh();
  
  // Print client terminal type
  mvprintw(2, 12, "[ Terminal type: %-20s ]", program.getTerminalType().c_str());
  
  char item[20];
  int ch = '?';
  int i = first_opt;

  WINDOW *menuWindow;
  WINDOW *descriptionWindow;
  
  menuWindow = newwin(8, 20, 5, 10);
  descriptionWindow = newwin(14, 50, 5, 31);
  
  keypad(menuWindow, TRUE);
   
  // Print menu message
  if(!rendererOptions.noColors) attron(COLOR_PAIR(2));
  mvprintw(26, 20, menu_message.c_str());
  if(!rendererOptions.noColors) attroff(COLOR_PAIR(2));
  refresh();
   
  do { 
  
    //clear();
    wclear(menuWindow);
    wclear(descriptionWindow);
    refresh();
  
    // Update menu depending on pressed keys
    switch(ch) {
      case KEY_UP:
        i--;
        i = (i<0)?2:i;
        break;
      case KEY_DOWN:
        i++;
        i = (i>2)?0:i;
        break;
    }
  
    // Print menu message
    if(!rendererOptions.noColors) attron(COLOR_PAIR(2));
    mvprintw(26, 20, menu_message.c_str());
    if(!rendererOptions.noColors) attroff(COLOR_PAIR(2));
  
    // Obtain current server time
    auto now = std::time(nullptr);
    std::stringstream ss;
    std::string nowDescription = "";
    ss << std::put_time(std::gmtime(&now), "%H:%M:%S");
    nowDescription = ss.str();
    
    // Print current server time
    mvprintw(3, 12, "[ Server time: %-20s   ]", nowDescription.c_str());
    
  
    // Render menu options
    for(int j=0; j<3; j++) {
      if(j==i) {
          if(!rendererOptions.noColors) wattron(menuWindow, A_STANDOUT);
      } else {
          if(!rendererOptions.noColors) wattroff(menuWindow, A_STANDOUT);
      }
      sprintf(item, "%-16s",  list[j].c_str());
      mvwprintw(menuWindow, j+2, 2, "%s", item);
    }
    
    sprintf(item, "%-16s",  list[i].c_str());
    
    box(menuWindow, 0, 0); 
    box(descriptionWindow, 0, 0);
    
    keypad(menuWindow, TRUE);
    wclear(descriptionWindow);
    box(descriptionWindow, 0, 0);
    
    // Render description box title
    if(!rendererOptions.noColors) wattron(descriptionWindow, COLOR_PAIR(1));
    mvwprintw(descriptionWindow, 3, 2, "[ %-10s ]", item);
    if(!rendererOptions.noColors) wattroff(descriptionWindow, COLOR_PAIR(1));
    
    // Render description box content
    mvwprintw(descriptionWindow, 5, 2, "%s", descriptions[i].c_str());
    box(descriptionWindow, 0, 0);
    wrefresh(descriptionWindow);
    
    // Refresh everything
    wrefresh(menuWindow);
    wrefresh(descriptionWindow);
    refresh();
    
    // Move cursor to the initial position
    move(0,0);
    addch(' ');
  } while((ch = wgetch(menuWindow)) != 10);

  delwin(descriptionWindow);
  delwin(menuWindow);
  
  return i;
}

/**
 * Initial menu
 */
int menu1(int first_opt, TermProgram& program) {
    
    // List of options
    std::string list[] = {
      "Opcja A",
      "Opcja B",
      "Koniec"
    };
    
    // List of descriptions
    std::string descriptions[] = {
      "Wybierz opcje A\n  Opcja A umozliwia duzo rzeczy :)",
      "Opcja B jest nawet lepsza niz opcja A\n  Czemu niby masz zawsze wybierac opcje A?\n  Nie dyskryminuj literek prosze :>",
      "E tam... Ide stad!"
    };
    
    int i = displayMenu(list, descriptions, first_opt, program);
    
    // When third option is selected we should terminate
    if(i == 2) {
      menu_end(program);
      return -1;
    }
    
    // For first option just display menu again and
    // change the message
    if(i == 0) {
      menu_message = "      @ Selected A       ";
      return menu1(i, program);
    }
    
    // For second option display the submenu
    return menu2(0, program);
}

/**
 * Submenu
 */
int menu2(int first_opt, TermProgram& program) {
   
    // List of options
    std::string list[] = {
      "Opcja B1",
      "Opcja B2",
      "Wstecz"
    };
    
    // List of descriptions
    std::string descriptions[] = {
      "Wybierz opcje B1\n  Opcja B1 umozliwia duzo rzeczy :)",
      "Opcja B2 jest nawet lepsza niz opcja B1\n  Czemu niby masz zawsze wybierac opcje B1?\n  Nie dyskryminuj cyferek prosze :>",
      "Moge wrocic spowrotem?"
    };
    
    // Display menu
    int i = displayMenu(list, descriptions, first_opt, program);
    
    // For third option go back to the initial menu
    if(i == 2) {
      return menu1(0, program);
    }
    
    // For first and second options just change
    // the messages and display again the same menu
    if(i == 0) {
      menu_message = "      @ Selected B1      ";
    } else {
      menu_message = "      @ Selected B2      ";
    }
    
    return menu2(i, program);
}

/**
 * Default application entrypoint
 */
void renderer(TermProgram& program) {
  
  // Check if colors are supported
  if(!rendererOptions.noColors) {
    if(has_colors() == FALSE) {
      rendererOptions.noColors = true;
    }
  }
  
  noecho();
  curs_set(0);
  
  // Run colors if they are supported
  if(!rendererOptions.noColors) {
    start_color();
    init_pair(1, COLOR_BLACK, COLOR_WHITE);
    init_pair(2, COLOR_WHITE, COLOR_BLUE);
  }
    
  // Start the application
  menu_start(program);

  echo();
  curs_set(1);
  refresh();
  endwin();
}

#endif /* __RENDERER__ */